# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LGBewcSl83I44ZQQoPBhduOWnRv9AKWi
"""

x = input("Lütfen 5 Değer Giriniz: ")
print(x)

print(type(1))
print(type(5.3))
print(type(f' python'))  ## f-string
print(type(7))
name2= "Büyükuçar"  ## format
print(type("berkay {}".format(name2))) ## format











